version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: nestuser
      DB_PASSWORD: nestpass
      DB_NAME: nestdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://rabbitmq
      JWT_SECRET: changeme
      JWT_EXPIRES_IN: 24h
    depends_on:
      - postgres
      - redis
      - rabbitmq

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
